common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
  path('login/',    
      auth_views.LoginView.as_view(template_name='common/login.html'), 
      name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index')

]

pybo/urls.py
from django.urls import path
# from .views import index, detail, answer_create
from . import views


# Function Based View: FBV
app_name = 'pybo'
urlpatterns = [
    path('', views.index, name='index'),    # config/urls.py에서 'pybo/' + '' --> 'pybo/'
    path('<int:question_id>/', views.detail, name='detail'),
    path('question/create/', views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', views.question_modify, name='question_modefy'),
    path('answer/create/<int:question_id>/', views.answer_create, 
         name='answer_create'),
    
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from tkinter.tix import Tree
from django.db import models
from django.contrib.auth.models import User

class Question(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  subject = models.CharField(max_length=200)
  content = models.TextField()
  create_date = models.DateTimeField()
  modify_date = models.DateTimeField(null=Tree, blank=Tree)

  def __str__(self):
    return self.subject

class Answer(models.Model):
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField()
  modify_date = models.DateTimeField(null=Tree, blank=Tree)

  def __str__(self):
    return self.content

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['subject', 'content']

    # widgets = {
    #   'subject': forms.TextInput(attrs={'class': 'form-control'}),
    #   'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 15}),
    # }

    labels = {
      'subject': '제목',
      'content': '내용',
    }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm

def signup(request):
  """
  계정생성
  """
  if request.method == "POST":
    form = UserForm(request.POST)
    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      raw_password = form.cleaned_data.get('password1')
      user = authenticate(username=username, password=raw_password)
      login(request, user)
      return redirect('index')
  else:
    form = UserForm()
  
  return render(request, 'common/signup.html', {'form': form})

pybo/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Question, Answer
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

from .forms import QuestionForm, AnswerForm

def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    # 조회
    question_list = Question.objects.order_by('-create_date')
    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}

    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    # question  = Question.objects.get(id = question_id)
    question  = get_object_or_404(Question, pk=question_id)
    context = { 'question': question}
    return render(request, 'pybo/quesiton_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question  = get_object_or_404(Question, pk=question_id)
    
    # content = request.POST['content'] # 'content' 키가 없으면 - 예외가 발생.
    content = request.POST.get('content')  # 'content' 키가 없으면 - None리턴

    # Answer 생성, 저장
    # 방법1]
    # answer = Answer(question = question, 
    #               content = content,
    #               create_date = timezone.now())
    # answer.save()

    # 방법2] ForeignKey 관계인경우
    # question.answer_set.create(content = content,
    #               create_date = timezone.now())

    # return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/quesiton_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
    pybo 질문수정
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question_author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)  


    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)



# def login(request, template_name):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
            
#             return redirect(LOGIN_REDIRECT_URL)
#     else:
#         form = LoginForm()

#     context = {'form': form}
#     return render(request, template_name, context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>pybo</title>

    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
      integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
  </head>
  <body>
    <div class="container">
      <div class="jumbotron mb-0 rounded-0">
        <h1>Pybo를 통한 Django 학습</h1>
        <p>Django와 Bootstrap을 이용한 사이트 구축 학습</p>
      </div>
      {% include 'navbar.html' %}
      <div class="my-3">{% block content %}{% endblock %}</div>
      <footer class="mt-5 p-3 bg-light">Copyright © created by xxxx. All right Reserved</footer>
    </div>

    <!-- jQuery JS -->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
  </body>
</html>

templates/common/login.html
{% extends "base.html" %} {% block content %}
<div class="login-form my-5 border rounded shadow-sm">
  <h3 class="mb-5"><i class="fas fa-sign-in-alt"></i> 로그인</h3>
  <form method="post" class="post-form" action="{% url 'common:login' %}">
    {% csrf_token %}

    <!-- 로그인 성공 후 이동되는 URL -->
    <input type="hidden" name="next" value="{{ next }}" />

    {% include "error/form_error.html" %}
    <div class="form-group">
      <label for="username"><i class="fas fa-user"></i> 사용자ID</label>
      <input
        type="text"
        class="form-control"
        name="username"
        placeholder="사용자 ID를 입력하세요."
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="form-group">
      <label for="password"><i class="fas fa-lock"></i> 비밀번호</label>
      <input
        type="password"
        class="form-control"
        name="password"
        placeholder="비밀번호를 입력하세요."
        id="password"
        value="{{ form.password.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary"><i class="fas fa-sign-in-alt mr-2"></i> 로그인</button>
    <a href="{%url 'common:signup' %}" class="btn btn-primary"><i class="fas fa-user-plus mr-2"></i> 회원가입</a>
  </form>
</div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %} {% block content %}
<div class="sign-up-form mt-5 border rounded shadow-sm">
  <h4 class="mb-5"><i class="fas fa-user-plus"></i> 계정생성</h4>
  <form method="post" class="post-form">
    {% csrf_token %} {% include "error/form_error.html" %}
    <div class="form-group">
      <label for="username">사용자 이름</label>
      <input
        type="text"
        class="form-control"
        name="username"
        placeholder="사용자 이름을 입력하세요."
        id="username"
        value="{{ form.username.value|default_if_none:'' }}"
      />
    </div>
    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input
        type="password"
        class="form-control"
        name="password1"
        placeholder="비밀번호를 입력하세요."
        id="password1"
        value="{{ form.password1.value|default_if_none:'' }}"
      />
    </div>
    <div class="form-group">
      <label for="password2">비밀번호 확인</label>
      <input
        type="password"
        class="form-control"
        name="password2"
        placeholder="확인용 비밀번호를 입력하세요."
        id="password2"
        value="{{ form.password2.value|default_if_none:'' }}"
      />
    </div>
    <div class="form-group">
      <label for="email">이메일</label>
      <input
        type="text"
        class="form-control"
        name="email"
        id="email"
        placeholder="email을 입력하세요."
        value="{{ form.email.value|default_if_none:'' }}"
      />
    </div>
    <button type="submit" class="btn btn-primary"><i class="fas fa-user-plus"></i> 생성하기</button>
  </form>
</div>
{% endblock %}

templates/navbar.html
{% load static %} {% static "" as baseUrl %}

<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom sticky-top">
  <a class="navbar-brand" href="{% url 'pybo:index' %}"><i class="fas fa-home"></i> Pybo</a>
  <button
    class="navbar-toggler ml-auto"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="#">
          <img src="{{baseUrl}}images/avatas/{{user.username}}.png" class="avata-sm rounded-circle" />
          {{ user.username }}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'common:logout' %}"> <i class="fas fa-sign-out-alt"></i> 로그아웃</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'common:login' %}"><i class="fas fa-sign-in-alt"></i> 로그인</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'common:signup' %}" class="nav-link"><i class="fas fa-user-plus"></i> 회원가입</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

templates/pagination.html
<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
  <!-- 이전페이지 -->
  {% if page_obj.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
      <i class="fas fa-chevron-left"></i>
    </a>
  </li>
  {% else %}
  <li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
      <i class="fas fa-chevron-left"></i>
    </a>
  </li>
  {% endif %}
  <!-- 페이지리스트 -->
  {% for page_number in page_obj.paginator.page_range %} {% if page_number >= page_obj.number|add:-3 and page_number <=
  page_obj.number|add:3 %} {% if page_number == page_obj.number %}
  <li class="page-item active" aria-current="page">
    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% else %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
  </li>
  {% endif %} {% endif %} {% endfor %}
  <!-- 다음페이지 -->
  {% if page_obj.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">
      <i class="fas fa-chevron-right"></i>
    </a>
  </li>
  {% else %}
  <li class="page-item disabled">
    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
      <i class="fas fa-chevron-right"></i>
    </a>
  </li>
  {% endif %}
</ul>

templates/pybo/quesiton_detail.html
{% extends 'base.html' %} {% block content %}

<h2 class="border-bottom py-2">{{ question.subject }}</h2>
<div class="card my-3">
  <div class="card-body">
    <div class="card-text" style="white-space: pre-line"><i class="far fa-question-circle"></i> {{ question.content }}</div>
    <div class="d-flex justify-content-end">
      <div class="badge badge-light p-2">
        <div class="mb-2">{{ question.author.username }}</div>
        <div><i class="fas fa-clock"></i> {{ question.create_date }}</div>
      </div>
    </div>
  </div>
</div>

<h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>

{% for answer in question.answer_set.all %}
<div class="card my-3">
  <div class="card-body">
    <div class="card-text" style="white-space: pre-line"><i class="fas fa-comment-dots"></i> {{ answer.content }}</div>
    <div class="d-flex justify-content-end">
      <div class="badge badge-light p-2">
        <div class="mb-2">{{ answer.author.username }}</div>
        <div><i class="fas fa-clock"></i> {{ answer.create_date }}</div>
      </div>
    </div>
    [%if request.user == question.author %]
    <div class="my-3">
      <a href="{ url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondart">수정</a>
    </div>
    {% endif %}
  </div>
  {% endfor %}

  <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %} {% include 'error/form_error.html' %}
    <div class="form-group">
      <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <button type="submit" class="btn btn-primary"><i class="fas fa-share-square"></i> 답변 등록</button>
    <a href="{% url 'pybo:index' %}" class="btn btn-primary"><i class="fas fa-list"></i> 목록 보기</a>
  </form>

  {% endblock content %}
</div>

templates/pybo/question_form.html
{% extends 'base.html' %}
<!-- content block 재정의 -->
{% block content %}

<h5 class="my-3 border-bottom pb-2">질문등록</h5>
<form method="post" class="post-form my-3">
  {% csrf_token %} {% include 'error/form_error.html' %}

  <div class="form-group">
    <label for="subject">{{form.subject.label}}</label>
    <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}" />
  </div>
  <div class="form-group">
    <label for="content">{{form.content.label}}</label>
    <textarea class="form-control" name="content" id="content" rows="10">{{form.content.value|default_if_none:''}}</textarea>
  </div>

  <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> 저장하기</button>
</form>

{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %} {% block content %}
<table class="table table-striped table-hover">
  <thead>
    <tr class="thead-dark">
      <th style="width: 60px">번호</th>
      <th>제목</th>
      <th style="width: 80px">글쓴이</th>
      <th style="width: 120px">작성일시</th>
    </tr>
  </thead>

  <tbody>
    {% if question_list %} {% for question in question_list %}
    <tr>
      <td>{{question.id}}</td>
      <td>
        <a href="{% url 'pybo:detail' question.id %}"> {{ question.subject }}</a>
        {% if question.answer_set.count > 0 %}
        <span class="badge badge-pill badge-primary"> {{question.answer_set.count}} </span>
        {% endif %}
      </td>
      <td>{{question.author.username}}</td>
      <td>{{ question.create_date | date:'Y-m-d' }}</td>
    </tr>
    {% endfor %} {% else %}
    <tr>
      <td colspan="3">질문이 없습니다.</td>
    </tr>
    {% endif %}
  </tbody>
</table>

{% include 'pagination.html' with page_obj=question_list %}

<div class="clearfix">
  <div class="float-left">
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary"><i class="fas fa-edit"></i> 질문 등록하기</a>
  </div>
  <div class="text-right float-right">(총: {{question_list.paginator.count}}건)</div>
</div>
{% endblock content %}